trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage : Build
   jobs:
   - job : FirstJob
     steps:
     - bash : echo Buildeploy job
     - bash : echo $(PipelineLevelVarible)
     - bash: echo $(Build.BuildNumber)
     - bash: echo $(Build.BuildId)
     - bash: echo $(Build.SourceDirectory)
     - bash: echo $(Build.DefaultWorkingDirectory)
     - bash: ls -R $(System.DefaultWorkingDirectory)
     - bash: ls -R $(Build.ArtifactStagingDirectory)
     - bash : java -version
     - bash: node --version
     - bash: mvn -version
     - bash: python --version
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: |
           **/*.yaml
           **/*.tf
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
     - bash: ls -R $(Build.ArtifactStagingDirectory)
     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'

  #  - job : SecondJob
  #    steps:
  #    - bash : echo build second job
  
#  - stage: DevDeploy
#    - job:DevDeployJob
#      steps:
#      - bash: echo DevDeploy job
#  - stage: QAdeploy
#    - job:QADeployJob
#      steps:
#      - bash: echo QAdeploy job
#  - stage: ProdDeploy
#    - job:ProdDeployJob
#      steps:
#      - bash: echo ProdDeploy job



 