# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage : Build
   jobs:
   - job : FirstJob
     steps:
     - bash : echo Buildeploy job
     - bash : echo $(PipelineLevelVarible)
     - bash: echo $(Build.BuildNumber)
     - bash: echo $(Build.BuildId)
     - bash: echo $(Build.SourceDirectory)
     - bash: echo $(Build.DefaultWorkingDirectory)
     - bash: ls -R $(System.DefaultWorkingDrectory)
     - bash: ls -R $(Build.StagingWorkingDirectory)
     - bash : java -version
     - bash: node --version
     - bash: mvn -version
     - bash: python --version
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDrectory)'
         Contents: |
           **/*.yaml
           **/*.tf
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
     - bash: ls -R $(Build.StagingWorkingDirectory)

  #  - job : SecondJob
  #    steps:
  #    - bash : echo build second job
  
#  - stage: DevDeploy
#    - job:DevDeployJob
#      steps:
#      - bash: echo DevDeploy job
#  - stage: QAdeploy
#    - job:QADeployJob
#      steps:
#      - bash: echo QAdeploy job
#  - stage: ProdDeploy
#    - job:ProdDeployJob
#      steps:
#      - bash: echo ProdDeploy job



 