# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage : Build
   jobs:
   - job : FirstJob
     steps:
     - bash : echo Buildeploy job
     - bash : echo $(PipelineLevelVarible)
     - bash: $(Build.BuildNumber)
     - bash: $(Build.BuildId)
     - bash: $(Build.SourceDirectory)
     - bash: $(Build.DefaultWorkingDirectory)
     - bash: $(System.DefaultWorkingDrectory)
   - job : SecondJob
     steps:
     - bash : echo build second job
  
#  - stage: DevDeploy
#    - job:DevDeployJob
#      steps:
#      - bash: echo DevDeploy job
#  - stage: QAdeploy
#    - job:QADeployJob
#      steps:
#      - bash: echo QAdeploy job
#  - stage: ProdDeploy
#    - job:ProdDeployJob
#      steps:
#      - bash: echo ProdDeploy job



 